make print statement python2/3 agnostic
While testing the course examples in a python3 interpreter. 

>>> print "We have lift off!"
  File "<stdin>", line 1
    print "We have lift off!"
                            ^
SyntaxError: invalid syntax

Convert to python3 style

>>> print("We have lift off!")
We have lift off!